### ISSUE TITLE
When the alarm is triggered, selected message does not pop up

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#132]
It bring a general pop-up saying "ぜん快ちゃんからのリマインダー"...
![IMG_0318](https://user-images.githubusercontent.com/61481039/120099366-050d6e00-c176-11eb-992f-956f3c4ea6b5.PNG)
![IMG_0319](https://user-images.githubusercontent.com/61481039/120099369-08a0f500-c176-11eb-8ec7-2d0a3229c7f1.PNG)

**Comment by rgagne** [comment]
should be fixed

**Comment by Show-M** [comment]
Chant, 3.0.2636
System ver: 14.5.1
Device: iPhone SE 

when i set the alarm on Chant

On chant app, alarm does not pop up any message now. (basically it does not do anything)

On Fluxweave app,  as I am on Asthma org, alarm gets triggered but the message is still the same as "ぜん快ちゃんからのリマインダー".

**Comment by rgagne** [comment]
Not sure why I said it was different. We have not yet implemented look up of name.

**Comment by Show-M** [comment]
it seems working now?

**Comment by rgagne** [comment]
Yes... rolled out a new server and then updated the script.

**Comment by rgagne** [comment]
FYI - you can have different default times:

![image](https://user-images.githubusercontent.com/428897/120879428-3797ea80-c5fe-11eb-8830-394186773f41.png)

**Comment by Show-M** [comment]
Is it possible not to have a default time from consiguration? 

When i do steps below, the system change the time back to default time of message i chose.
![1](https://user-images.githubusercontent.com/61481039/120891958-85384580-c646-11eb-9fec-391367f88d16.gif)
